AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TableName:
    Type: String
  ReadCapacityUnits:
    Type: Number
  WriteCapacityUnits:
    Type: Number
Resources:
  MyDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

Outputs:
  AccountId:
    Value: !Sub "${AWS::AccountId}"
    Export:
      Name: "MyStack-AccountId"
  Region:
    Value: !Sub "${AWS::Region}"
    Export:
      Name: "MyStack-Region"
